apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tv-assets-service
    app.kubernetes.io/instance: tv-assets-service-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: tv-assets-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tv-assets-service
  template:
    metadata:
      labels:
        app: tv-assets-service
    spec:
      containers:
        - image: 663319559600.dkr.ecr.eu-west-2.amazonaws.com/tv-assets-service-uat:latest
          imagePullPolicy: Always
          name: tv-assets-service
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: tv-assets-service-config
            - secretRef:
                name: tv-assets-service-secret
